# PyTorch Basics

Following along with these tutorials:
- https://github.com/udacity/DL_PyTorch
- https://pytorch.org/tutorials/beginner/deep_learning_nlp_tutorial.html

In [16]:
import numpy as np
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

## Tensor Library

In [17]:
x = torch.rand(3, 2)
x

tensor([[ 0.7576,  0.2793],
        [ 0.4031,  0.7347],
        [ 0.0293,  0.7999]])

In [18]:
y = torch.ones(x.size())
y

tensor([[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]])

In [19]:
z = x + y
z

tensor([[ 1.7576,  1.2793],
        [ 1.4031,  1.7347],
        [ 1.0293,  1.7999]])

In [20]:
z[0]

tensor([ 1.7576,  1.2793])

In [21]:
z[:, 1:]

tensor([[ 1.2793],
        [ 1.7347],
        [ 1.7999]])

Tensors typically have two forms of methods, one method that returns another tensor and another method that performs the operation in place. That is, the values in memory for that tensor are changed without creating a new tensor. In-place functions are always followed by an underscore, for example `z.add()` and `z.add_()`.

In [22]:
# Return a new tensor z + 1
z.add(1)

tensor([[ 2.7576,  2.2793],
        [ 2.4031,  2.7347],
        [ 2.0293,  2.7999]])

In [23]:
# z tensor is unchanged
z

tensor([[ 1.7576,  1.2793],
        [ 1.4031,  1.7347],
        [ 1.0293,  1.7999]])

In [24]:
# Add 1 and update z tensor in-place
z.add_(1)

tensor([[ 2.7576,  2.2793],
        [ 2.4031,  2.7347],
        [ 2.0293,  2.7999]])

In [25]:
# z has been updated
z

tensor([[ 2.7576,  2.2793],
        [ 2.4031,  2.7347],
        [ 2.0293,  2.7999]])

In [2]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([ 1.,  2.,  3.])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]]])


In [3]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

# Index into M and get a vector
print(M[0])

# Index into T and get a matrix
print(T[0])

tensor(1.)
1.0
tensor([ 1.,  2.,  3.])
tensor([[ 1.,  2.],
        [ 3.,  4.]])


In [4]:
# Generate a tensor with random data
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


In [5]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([ 5.,  7.,  9.])


In [6]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])
print(z_1)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)

# If your tensors are not compatible, torch will complain.  Uncomment to see the error
# torch.cat([x_1, x_2])

tensor([[-0.8029,  0.2366,  0.2857,  0.6898, -0.6331],
        [ 0.8795, -0.6842,  0.4533,  0.2912, -0.8317],
        [-0.5525,  0.6355, -0.3968, -0.6571, -1.6428],
        [ 0.9803, -0.0421, -0.8206,  0.3133, -1.1352],
        [ 0.3773, -0.2824, -2.5667, -1.4303,  0.5009]])
tensor([[ 0.5438, -0.4057,  1.1341, -0.1473,  0.6272,  1.0935,  0.0939,
          1.2381],
        [-1.1115,  0.3501, -0.7703, -1.3459,  0.5119, -0.6933, -0.1668,
         -0.9999]])


In [7]:
# Reshaping tensors
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))  # Reshape to 2 rows, 12 columns
# Same as above.  If one of the dimensions is -1, its size can be inferred
print(x.view(2, -1))

tensor([[[ 0.4175, -0.2127, -0.8400, -0.4200],
         [-0.6240, -0.9773,  0.8748,  0.9873],
         [-0.0594, -2.4919,  0.2423,  0.2883]],

        [[-0.1095,  0.3126,  1.5038,  0.5038],
         [ 0.6223, -0.4481, -0.2856,  0.3880],
         [-1.1435, -0.6512, -0.1032,  0.6937]]])
tensor([[ 0.4175, -0.2127, -0.8400, -0.4200, -0.6240, -0.9773,  0.8748,
          0.9873, -0.0594, -2.4919,  0.2423,  0.2883],
        [-0.1095,  0.3126,  1.5038,  0.5038,  0.6223, -0.4481, -0.2856,
          0.3880, -1.1435, -0.6512, -0.1032,  0.6937]])
tensor([[ 0.4175, -0.2127, -0.8400, -0.4200, -0.6240, -0.9773,  0.8748,
          0.9873, -0.0594, -2.4919,  0.2423,  0.2883],
        [-0.1095,  0.3126,  1.5038,  0.5038,  0.6223, -0.4481, -0.2856,
          0.3880, -1.1435, -0.6512, -0.1032,  0.6937]])


In [26]:
z.size()

torch.Size([3, 2])

In [27]:
z.resize_(2, 3)

tensor([[ 2.7576,  2.2793,  2.4031],
        [ 2.7347,  2.0293,  2.7999]])

In [29]:
z

tensor([[ 2.7576,  2.2793,  2.4031],
        [ 2.7347,  2.0293,  2.7999]])

## Numpy to Torch and Back

Converting between Numpy arrays and Torch tensors is super simple and useful. To create a tensor from a Numpy array, use `torch.from_numpy()`. To convert a tensor to a Numpy array, use the `.numpy()` method.

In [30]:
a = np.random.rand(4,3)
a

array([[0.80723677, 0.02946084, 0.18012851],
       [0.31984501, 0.86435952, 0.92777395],
       [0.2881922 , 0.5860244 , 0.17808662],
       [0.25321784, 0.63862476, 0.98670205]])

In [31]:
b = torch.from_numpy(a)
b

tensor([[ 0.8072,  0.0295,  0.1801],
        [ 0.3198,  0.8644,  0.9278],
        [ 0.2882,  0.5860,  0.1781],
        [ 0.2532,  0.6386,  0.9867]], dtype=torch.float64)

In [32]:
b.numpy()

array([[0.80723677, 0.02946084, 0.18012851],
       [0.31984501, 0.86435952, 0.92777395],
       [0.2881922 , 0.5860244 , 0.17808662],
       [0.25321784, 0.63862476, 0.98670205]])

The memory is shared between the Numpy array and Torch tensor, so if you change the values in-place of one object, the other will change as well.

In [33]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[ 1.6145,  0.0589,  0.3603],
        [ 0.6397,  1.7287,  1.8555],
        [ 0.5764,  1.1720,  0.3562],
        [ 0.5064,  1.2772,  1.9734]], dtype=torch.float64)

In [34]:
# Numpy array matches new values from Tensor
a

array([[1.61447355, 0.05892167, 0.36025701],
       [0.63969001, 1.72871903, 1.8555479 ],
       [0.57638441, 1.1720488 , 0.35617324],
       [0.50643569, 1.27724952, 1.9734041 ]])

## Computation Graphs and Automatic Differentiation

The concept of a computation graph is essential to efficient deep learning programming, because it allows you to not have to write the back propagation gradients yourself. A computation graph is simply a specification of how your data is combined to give you the output. Since the graph totally specifies what parameters were involved with which operations, it contains enough information to compute derivatives.

In [8]:
# Tensor factory methods have a ``requires_grad`` flag
x = torch.tensor([1., 2., 3.], requires_grad=True)

# With requires_grad=True, you can still do all the operations you previously
# could
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x + y
print(z)

# BUT z knows something extra.
print(z.grad_fn)

tensor([ 5.,  7.,  9.])


In [11]:
print(x.grad_fn)
print(y.grad_fn)

None
None


In [12]:
# Lets sum up all the entries in z
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21.)


Lets have Pytorch compute the gradient, and see that we were right: (note if you run this block multiple times, the gradient will increment. That is because Pytorch accumulates the gradient into the .grad property, since for many models this is very convenient.)

In [13]:
# Calling .backward() on any variable will run backprop, starting from it
s.backward()
print(x.grad)

tensor([ 1.,  1.,  1.])


Understanding what is going on in the block below is crucial for being a successful programmer in deep learning.

In [14]:
x = torch.randn(2, 2)
y = torch.randn(2, 2)
# By default, user-created Tensors have ``requires_grad=False``
print(x.requires_grad, y.requires_grad)
z = x + y
# So you can't backprop through z
print(z.grad_fn)

# ``.requires_grad_( ... )`` changes an existing Tensor's ``requires_grad``
# flag in-place. The input flag defaults to ``True`` if not given.
x = x.requires_grad_()
y = y.requires_grad_()
# z contains enough information to compute gradients, as we saw above
z = x + y
print(z.grad_fn)
# If any input to an operation has ``requires_grad=True``, so will the output
print(z.requires_grad)

# Now z has the computation history that relates itself to x and y
# Can we just take its values, and **detach** it from its history?
new_z = z.detach()

# ... does new_z have information to backprop to x and y?
# NO!
print(new_z.grad_fn)
# And how could it? ``z.detach()`` returns a tensor that shares the same storage
# as ``z``, but with the computation history forgotten. It doesn't know anything
# about how it was computed.
# In essence, we have broken the Tensor away from its past history

False False
None
True
None


You can also stop autograd from tracking history on Tensors with `.requires_grad=True` by wrapping the code block in `with torch.no_grad()`.

In [15]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
